
#
# do not edit this file, it is generated by tools/generate_build_info.py
#

TIMESTAMP = '2018-03-10 14:39:53'
SYSTEM = 'Linux 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018'
COMMIT = 'f1eafb99d96b9333cebd5a077be269b90618ab02'
STATUS = ['?? src/build_info.py', '?? tools/']
USER = 'linluk'
PACKAGES = ['altgraph==0.15', 'future==0.16.0', 'macholib==1.9', 'mypy==0.560', 'pefile==2017.11.5', 'pkg-resources==0.0.0', 'psutil==5.4.3', 'pygame==1.9.3', 'PyInstaller==3.3.1', 'typed-ast==1.1.0']
